image: python:3.6-alpine

# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

# build_frontend:
#   image: node:alpine
#   before_script:
#     - node -v
#     - yarn -v
#   script:
#     - cd frontend
#     - yarn install
#     - node_modules/.bin/webpack

run_backend:
  image: python:3.6-alpine
  before_script:
    - python -V
    - apk --update add --no-cache --virtual .build_deps build-base git python3-dev libffi-dev jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
  services:
    - postgres:alpine
    - redis:alpine
  script:
    - python -m pip install -Ur requirements.txt
    - mkdir frontend/output admin-panel/dist -p
    - touch frontend/output/index.html admin-panel/dist/index.html
    - cat config.py.example config.py.ci > config.py
    - python run.py
  after_script:
    - apk del .build_deps
