version: '2'
services:
    elixire:
        build: .
        depends_on:
            - postgres
            - redis
        volumes:
            - ./:/elixire
        ports:
            - "8080:8080"

    postgres:
        image: "postgres:10.1"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

    redis:
        image: "redis:4.0.9"
